version: '3.9'

services:
  backend:
    build: ../../backend/sistemap-backend
    container_name: sistemapj-backend
    ports:
      - '8080:8080'
    env_file:
      - ../../backend/sistemap-backend/.env

  frontend:
    build: .
    container_name: sistemapj-frontend
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080/v1
    ports:
      - '3000:3000'

